FROM adoptopenjdk/openjdk11:alpine 
RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring
COPY ./target/devops-escola.jar /app/devops-escola.jar
WORKDIR /app
EXPORT DISPLAY="localhost:10.0"
ENTRYPOINT ["java", "-jar", "devops-escola.jar"]