FROM adoptopenjdk/openjdk11:alpine 
RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring
COPY ./target/devops-escola.jar /app/devops-escola.jar
WORKDIR /app
EXPORT DISPLAY="localhost:10.0"
ENTRYPOINT ["java", "-jar", "devops-escola.jar"]

# Firefox over VNC
#
# VERSION               0.1
# DOCKER-VERSION        0.2

FROM    ubuntu:14.04
# Make sure the package repository is up to date
RUN     apt-get update

# Install vnc, xvfb in order to create a 'fake' display and firefox
RUN     apt-get install -y x11vnc xvfb firefox
RUN     mkdir ~/.vnc
# Setup a password
RUN     x11vnc -storepasswd 1234 ~/.vnc/passwd
# Autostart firefox (might not be the best way to do it, but it does the trick)
RUN     bash -c 'echo "firefox" >> /.bashrc'
