name: 'CI-JUNIT-V5'
on:
  pull_request:

jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      #- name: Build and Run Tests
      #  run: # execute your tests generating test results
        
      - name: Build and Run Tests
        #run: mvn --batch-mode -DskipTests package
        run: mvn -B package --file pom.xml

      - name: Test
        #run: mvn --batch-mode -Dmaven.test.failure.ignore=true test
        run: mvn clean test -pl :devops -Dtest=UnitTests
                
#      - name: Publish Test Report
#        uses: mikepenz/action-junit-report@v4
#        if: success() || failure() # always run even if the previous step fails
#        with:
#          report_paths: '**/build/test-results/test/TEST-*.xml'